stages: 
    - build
    - test

# caching per branch
# To avoid to dl gradle each time
cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .gradle
    - build
    - config.properties

# caching apt
# To avoid to dl everything each time
cache:
  key: "apt-cache"
  paths:
    - apt-cache

before_script:
  - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
  - apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y openjdk-8-jdk git

# Main build 
build: 
  stage: build
  image: ubuntu:16.04
  tags:
    - docker 
  script:
    - ./gradlew assemble


 # Tests
tests:
  stage: test
  image: ubuntu:16.04
  tags:
    - docker 
  dependencies:
    - build
  script:
    - ./gradlew test    
  artifacts:
    when: always
    paths:
      # Tests coverage report and Unit test result
      - build/*
    expire_in: 8d
  except:
    - master
 
 
#selenium:
#  stage: test
#  image: selenium/standalone-firefox
#  tags:
#    - docker 
#  script:
#    - "sudo apt-get update"
#    - "sudo apt-get -y install openjdk-8-jdk"
#    - ./gradlew selenium

